# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: (c) 2026 Tim Bode, PGI-12, Forschungszentrum Jülich
# Autogenerated using ProtoBuf.jl v1.3.0
# original file: quicopt/modeler/v1/program.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export OpDef, Bound, IndexElem, Domain, Nonneg, Zero, Catalog, Index, IndexSet, VarDecl
export SetRef, FixEntry, ParamRef, VarRef, ParamEntry, IndexedSetFibre, QuantBinding
export ParamTable, IndexedSet, ParamData, Apply, ConSet, Indicator, Reduce, Constraint
export Expression, Program
abstract type var"##Abstract#ConSet" end
abstract type var"##Abstract#Constraint" end
abstract type var"##Abstract#Indicator" end
abstract type var"##Abstract#Program" end
abstract type var"##Abstract#Apply" end
abstract type var"##Abstract#Reduce" end
abstract type var"##Abstract#Expression" end


struct OpDef
    op::String
    arity::Int32
    tags::Vector{String}
end
OpDef(;op = "", arity = zero(Int32), tags = Vector{String}()) = OpDef(op, arity, tags)
PB.default_values(::Type{OpDef}) = (;op = "", arity = zero(Int32), tags = Vector{String}())
PB.field_numbers(::Type{OpDef}) = (;op = 1, arity = 2, tags = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OpDef}, _endpos::Int=0, _group::Bool=false)
    op = ""
    arity = zero(Int32)
    tags = PB.BufferedVector{String}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            op = PB.decode(d, String)
        elseif field_number == 2
            arity = PB.decode(d, Int32)
        elseif field_number == 3
            PB.decode!(d, tags)
        else
            Base.skip(d, wire_type)
        end
    end
    return OpDef(op, arity, tags[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OpDef)
    initpos = position(e.io)
    !isempty(x.op) && PB.encode(e, 1, x.op)
    x.arity != zero(Int32) && PB.encode(e, 2, x.arity)
    !isempty(x.tags) && PB.encode(e, 3, x.tags)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OpDef)
    encoded_size = 0
    !isempty(x.op) && (encoded_size += PB._encoded_size(x.op, 1))
    x.arity != zero(Int32) && (encoded_size += PB._encoded_size(x.arity, 2))
    !isempty(x.tags) && (encoded_size += PB._encoded_size(x.tags, 3))
    return encoded_size
end

struct Bound
    kind::Union{Nothing,OneOf{<:Union{Float64,String}}}
end
Bound(;kind = nothing) = Bound(kind)
PB.oneof_field_types(::Type{Bound}) = (;
    kind = (;scalar=Float64, param=String),
)
PB.default_values(::Type{Bound}) = (;scalar = zero(Float64), param = "")
PB.field_numbers(::Type{Bound}) = (;scalar = 1, param = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Bound}, _endpos::Int=0, _group::Bool=false)
    kind = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            kind = OneOf(:scalar, PB.decode(d, Float64))
        elseif field_number == 2
            kind = OneOf(:param, PB.decode(d, String))
        else
            Base.skip(d, wire_type)
        end
    end
    return Bound(kind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Bound)
    initpos = position(e.io)
    if isnothing(x.kind);
    elseif x.kind.name === :scalar
        PB.encode(e, 1, x.kind[]::Float64)
    elseif x.kind.name === :param
        PB.encode(e, 2, x.kind[]::String)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Bound)
    encoded_size = 0
    if isnothing(x.kind);
    elseif x.kind.name === :scalar
        encoded_size += PB._encoded_size(x.kind[]::Float64, 1)
    elseif x.kind.name === :param
        encoded_size += PB._encoded_size(x.kind[]::String, 2)
    end
    return encoded_size
end

struct IndexElem
    kind::Union{Nothing,OneOf{<:Union{Int64,String}}}
end
IndexElem(;kind = nothing) = IndexElem(kind)
PB.oneof_field_types(::Type{IndexElem}) = (;
    kind = (;int=Int64, name=String),
)
PB.default_values(::Type{IndexElem}) = (;int = zero(Int64), name = "")
PB.field_numbers(::Type{IndexElem}) = (;int = 1, name = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IndexElem}, _endpos::Int=0, _group::Bool=false)
    kind = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            kind = OneOf(:int, PB.decode(d, Int64))
        elseif field_number == 2
            kind = OneOf(:name, PB.decode(d, String))
        else
            Base.skip(d, wire_type)
        end
    end
    return IndexElem(kind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IndexElem)
    initpos = position(e.io)
    if isnothing(x.kind);
    elseif x.kind.name === :int
        PB.encode(e, 1, x.kind[]::Int64)
    elseif x.kind.name === :name
        PB.encode(e, 2, x.kind[]::String)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::IndexElem)
    encoded_size = 0
    if isnothing(x.kind);
    elseif x.kind.name === :int
        encoded_size += PB._encoded_size(x.kind[]::Int64, 1)
    elseif x.kind.name === :name
        encoded_size += PB._encoded_size(x.kind[]::String, 2)
    end
    return encoded_size
end

@enumx Domain DOMAIN_UNSPECIFIED=0 CONTINUOUS=1 INTEGER=2 BINARY=3

struct Nonneg end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Nonneg}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return Nonneg()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Nonneg)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Nonneg)
    encoded_size = 0
    return encoded_size
end

struct Zero end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Zero}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return Zero()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Zero)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Zero)
    encoded_size = 0
    return encoded_size
end

struct Catalog
    version::UInt32
    ops::Vector{OpDef}
end
Catalog(;version = zero(UInt32), ops = Vector{OpDef}()) = Catalog(version, ops)
PB.default_values(::Type{Catalog}) = (;version = zero(UInt32), ops = Vector{OpDef}())
PB.field_numbers(::Type{Catalog}) = (;version = 1, ops = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Catalog}, _endpos::Int=0, _group::Bool=false)
    version = zero(UInt32)
    ops = PB.BufferedVector{OpDef}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            version = PB.decode(d, UInt32)
        elseif field_number == 2
            PB.decode!(d, ops)
        else
            Base.skip(d, wire_type)
        end
    end
    return Catalog(version, ops[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Catalog)
    initpos = position(e.io)
    x.version != zero(UInt32) && PB.encode(e, 1, x.version)
    !isempty(x.ops) && PB.encode(e, 2, x.ops)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Catalog)
    encoded_size = 0
    x.version != zero(UInt32) && (encoded_size += PB._encoded_size(x.version, 1))
    !isempty(x.ops) && (encoded_size += PB._encoded_size(x.ops, 2))
    return encoded_size
end

struct Index
    elems::Vector{IndexElem}
end
Index(;elems = Vector{IndexElem}()) = Index(elems)
PB.default_values(::Type{Index}) = (;elems = Vector{IndexElem}())
PB.field_numbers(::Type{Index}) = (;elems = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Index}, _endpos::Int=0, _group::Bool=false)
    elems = PB.BufferedVector{IndexElem}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, elems)
        else
            Base.skip(d, wire_type)
        end
    end
    return Index(elems[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Index)
    initpos = position(e.io)
    !isempty(x.elems) && PB.encode(e, 1, x.elems)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Index)
    encoded_size = 0
    !isempty(x.elems) && (encoded_size += PB._encoded_size(x.elems, 1))
    return encoded_size
end

struct IndexSet
    name::String
    elements::Vector{IndexElem}
end
IndexSet(;name = "", elements = Vector{IndexElem}()) = IndexSet(name, elements)
PB.default_values(::Type{IndexSet}) = (;name = "", elements = Vector{IndexElem}())
PB.field_numbers(::Type{IndexSet}) = (;name = 1, elements = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IndexSet}, _endpos::Int=0, _group::Bool=false)
    name = ""
    elements = PB.BufferedVector{IndexElem}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, elements)
        else
            Base.skip(d, wire_type)
        end
    end
    return IndexSet(name, elements[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IndexSet)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.elements) && PB.encode(e, 2, x.elements)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IndexSet)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.elements) && (encoded_size += PB._encoded_size(x.elements, 2))
    return encoded_size
end

struct VarDecl
    name::String
    axes::Vector{String}
    domain::Domain.T
    lower::Union{Nothing,Bound}
    upper::Union{Nothing,Bound}
    start::Float64
end
VarDecl(;name = "", axes = Vector{String}(), domain = Domain.DOMAIN_UNSPECIFIED, lower = nothing, upper = nothing, start = zero(Float64)) = VarDecl(name, axes, domain, lower, upper, start)
PB.default_values(::Type{VarDecl}) = (;name = "", axes = Vector{String}(), domain = Domain.DOMAIN_UNSPECIFIED, lower = nothing, upper = nothing, start = zero(Float64))
PB.field_numbers(::Type{VarDecl}) = (;name = 1, axes = 2, domain = 3, lower = 4, upper = 5, start = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VarDecl}, _endpos::Int=0, _group::Bool=false)
    name = ""
    axes = PB.BufferedVector{String}()
    domain = Domain.DOMAIN_UNSPECIFIED
    lower = Ref{Union{Nothing,Bound}}(nothing)
    upper = Ref{Union{Nothing,Bound}}(nothing)
    start = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, axes)
        elseif field_number == 3
            domain = PB.decode(d, Domain.T)
        elseif field_number == 4
            PB.decode!(d, lower)
        elseif field_number == 5
            PB.decode!(d, upper)
        elseif field_number == 6
            start = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return VarDecl(name, axes[], domain, lower[], upper[], start)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VarDecl)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.axes) && PB.encode(e, 2, x.axes)
    x.domain != Domain.DOMAIN_UNSPECIFIED && PB.encode(e, 3, x.domain)
    !isnothing(x.lower) && PB.encode(e, 4, x.lower)
    !isnothing(x.upper) && PB.encode(e, 5, x.upper)
    x.start !== zero(Float64) && PB.encode(e, 6, x.start)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VarDecl)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.axes) && (encoded_size += PB._encoded_size(x.axes, 2))
    x.domain != Domain.DOMAIN_UNSPECIFIED && (encoded_size += PB._encoded_size(x.domain, 3))
    !isnothing(x.lower) && (encoded_size += PB._encoded_size(x.lower, 4))
    !isnothing(x.upper) && (encoded_size += PB._encoded_size(x.upper, 5))
    x.start !== zero(Float64) && (encoded_size += PB._encoded_size(x.start, 6))
    return encoded_size
end

struct SetRef
    name::String
    args::Union{Nothing,Index}
end
SetRef(;name = "", args = nothing) = SetRef(name, args)
PB.default_values(::Type{SetRef}) = (;name = "", args = nothing)
PB.field_numbers(::Type{SetRef}) = (;name = 1, args = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetRef}, _endpos::Int=0, _group::Bool=false)
    name = ""
    args = Ref{Union{Nothing,Index}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetRef(name, args[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetRef)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isnothing(x.args) && PB.encode(e, 2, x.args)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetRef)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isnothing(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    return encoded_size
end

struct FixEntry
    var::String
    index::Union{Nothing,Index}
    value::Float64
end
FixEntry(;var = "", index = nothing, value = zero(Float64)) = FixEntry(var, index, value)
PB.default_values(::Type{FixEntry}) = (;var = "", index = nothing, value = zero(Float64))
PB.field_numbers(::Type{FixEntry}) = (;var = 1, index = 2, value = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FixEntry}, _endpos::Int=0, _group::Bool=false)
    var = ""
    index = Ref{Union{Nothing,Index}}(nothing)
    value = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            var = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, index)
        elseif field_number == 3
            value = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return FixEntry(var, index[], value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FixEntry)
    initpos = position(e.io)
    !isempty(x.var) && PB.encode(e, 1, x.var)
    !isnothing(x.index) && PB.encode(e, 2, x.index)
    x.value !== zero(Float64) && PB.encode(e, 3, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FixEntry)
    encoded_size = 0
    !isempty(x.var) && (encoded_size += PB._encoded_size(x.var, 1))
    !isnothing(x.index) && (encoded_size += PB._encoded_size(x.index, 2))
    x.value !== zero(Float64) && (encoded_size += PB._encoded_size(x.value, 3))
    return encoded_size
end

struct ParamRef
    name::String
    index::Union{Nothing,Index}
end
ParamRef(;name = "", index = nothing) = ParamRef(name, index)
PB.default_values(::Type{ParamRef}) = (;name = "", index = nothing)
PB.field_numbers(::Type{ParamRef}) = (;name = 1, index = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ParamRef}, _endpos::Int=0, _group::Bool=false)
    name = ""
    index = Ref{Union{Nothing,Index}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, index)
        else
            Base.skip(d, wire_type)
        end
    end
    return ParamRef(name, index[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ParamRef)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isnothing(x.index) && PB.encode(e, 2, x.index)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ParamRef)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isnothing(x.index) && (encoded_size += PB._encoded_size(x.index, 2))
    return encoded_size
end

struct VarRef
    name::String
    index::Union{Nothing,Index}
end
VarRef(;name = "", index = nothing) = VarRef(name, index)
PB.default_values(::Type{VarRef}) = (;name = "", index = nothing)
PB.field_numbers(::Type{VarRef}) = (;name = 1, index = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VarRef}, _endpos::Int=0, _group::Bool=false)
    name = ""
    index = Ref{Union{Nothing,Index}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, index)
        else
            Base.skip(d, wire_type)
        end
    end
    return VarRef(name, index[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VarRef)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isnothing(x.index) && PB.encode(e, 2, x.index)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VarRef)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isnothing(x.index) && (encoded_size += PB._encoded_size(x.index, 2))
    return encoded_size
end

struct ParamEntry
    key::Union{Nothing,Index}
    value::Float64
end
ParamEntry(;key = nothing, value = zero(Float64)) = ParamEntry(key, value)
PB.default_values(::Type{ParamEntry}) = (;key = nothing, value = zero(Float64))
PB.field_numbers(::Type{ParamEntry}) = (;key = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ParamEntry}, _endpos::Int=0, _group::Bool=false)
    key = Ref{Union{Nothing,Index}}(nothing)
    value = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, key)
        elseif field_number == 2
            value = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return ParamEntry(key[], value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ParamEntry)
    initpos = position(e.io)
    !isnothing(x.key) && PB.encode(e, 1, x.key)
    x.value !== zero(Float64) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ParamEntry)
    encoded_size = 0
    !isnothing(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    x.value !== zero(Float64) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct IndexedSetFibre
    key::Union{Nothing,Index}
    value::Vector{IndexElem}
end
IndexedSetFibre(;key = nothing, value = Vector{IndexElem}()) = IndexedSetFibre(key, value)
PB.default_values(::Type{IndexedSetFibre}) = (;key = nothing, value = Vector{IndexElem}())
PB.field_numbers(::Type{IndexedSetFibre}) = (;key = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IndexedSetFibre}, _endpos::Int=0, _group::Bool=false)
    key = Ref{Union{Nothing,Index}}(nothing)
    value = PB.BufferedVector{IndexElem}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, key)
        elseif field_number == 2
            PB.decode!(d, value)
        else
            Base.skip(d, wire_type)
        end
    end
    return IndexedSetFibre(key[], value[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IndexedSetFibre)
    initpos = position(e.io)
    !isnothing(x.key) && PB.encode(e, 1, x.key)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IndexedSetFibre)
    encoded_size = 0
    !isnothing(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct QuantBinding
    idx::String
    set::Union{Nothing,SetRef}
end
QuantBinding(;idx = "", set = nothing) = QuantBinding(idx, set)
PB.default_values(::Type{QuantBinding}) = (;idx = "", set = nothing)
PB.field_numbers(::Type{QuantBinding}) = (;idx = 1, set = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:QuantBinding}, _endpos::Int=0, _group::Bool=false)
    idx = ""
    set = Ref{Union{Nothing,SetRef}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            idx = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, set)
        else
            Base.skip(d, wire_type)
        end
    end
    return QuantBinding(idx, set[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::QuantBinding)
    initpos = position(e.io)
    !isempty(x.idx) && PB.encode(e, 1, x.idx)
    !isnothing(x.set) && PB.encode(e, 2, x.set)
    return position(e.io) - initpos
end
function PB._encoded_size(x::QuantBinding)
    encoded_size = 0
    !isempty(x.idx) && (encoded_size += PB._encoded_size(x.idx, 1))
    !isnothing(x.set) && (encoded_size += PB._encoded_size(x.set, 2))
    return encoded_size
end

struct ParamTable
    name::String
    entries::Vector{ParamEntry}
end
ParamTable(;name = "", entries = Vector{ParamEntry}()) = ParamTable(name, entries)
PB.default_values(::Type{ParamTable}) = (;name = "", entries = Vector{ParamEntry}())
PB.field_numbers(::Type{ParamTable}) = (;name = 1, entries = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ParamTable}, _endpos::Int=0, _group::Bool=false)
    name = ""
    entries = PB.BufferedVector{ParamEntry}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, entries)
        else
            Base.skip(d, wire_type)
        end
    end
    return ParamTable(name, entries[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ParamTable)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.entries) && PB.encode(e, 2, x.entries)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ParamTable)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.entries) && (encoded_size += PB._encoded_size(x.entries, 2))
    return encoded_size
end

struct IndexedSet
    name::String
    fibres::Vector{IndexedSetFibre}
end
IndexedSet(;name = "", fibres = Vector{IndexedSetFibre}()) = IndexedSet(name, fibres)
PB.default_values(::Type{IndexedSet}) = (;name = "", fibres = Vector{IndexedSetFibre}())
PB.field_numbers(::Type{IndexedSet}) = (;name = 1, fibres = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IndexedSet}, _endpos::Int=0, _group::Bool=false)
    name = ""
    fibres = PB.BufferedVector{IndexedSetFibre}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, fibres)
        else
            Base.skip(d, wire_type)
        end
    end
    return IndexedSet(name, fibres[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IndexedSet)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.fibres) && PB.encode(e, 2, x.fibres)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IndexedSet)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.fibres) && (encoded_size += PB._encoded_size(x.fibres, 2))
    return encoded_size
end

struct ParamData
    params::Vector{ParamTable}
end
ParamData(;params = Vector{ParamTable}()) = ParamData(params)
PB.default_values(::Type{ParamData}) = (;params = Vector{ParamTable}())
PB.field_numbers(::Type{ParamData}) = (;params = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ParamData}, _endpos::Int=0, _group::Bool=false)
    params = PB.BufferedVector{ParamTable}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, params)
        else
            Base.skip(d, wire_type)
        end
    end
    return ParamData(params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ParamData)
    initpos = position(e.io)
    !isempty(x.params) && PB.encode(e, 1, x.params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ParamData)
    encoded_size = 0
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 1))
    return encoded_size
end

# Stub definitions for cyclic types
struct var"##Stub#Apply"{T1<:var"##Abstract#Expression"} <: var"##Abstract#Apply"
    op::String
    args::Vector{T1}
end

struct var"##Stub#ConSet"{T1<:var"##Abstract#Indicator"} <: var"##Abstract#ConSet"
    kind::Union{Nothing,OneOf{<:Union{Zero,Nonneg,T1}}}
end

struct var"##Stub#Indicator" <: var"##Abstract#Indicator"
    bin::Union{Nothing,VarRef}
    inner::Union{Nothing,var"##Stub#ConSet"{var"##Stub#Indicator"}}
end

struct var"##Stub#Reduce"{T1<:var"##Abstract#Expression"} <: var"##Abstract#Reduce"
    op::String
    idx::String
    over::Union{Nothing,SetRef}
    body::Union{Nothing,T1}
    cond::Union{Nothing,T1}
end

struct var"##Stub#Constraint"{T1<:var"##Abstract#Expression"} <: var"##Abstract#Constraint"
    f::Union{Nothing,T1}
    set::Union{Nothing,var"##Stub#ConSet"{var"##Stub#Indicator"}}
    over::Vector{QuantBinding}
end

struct var"##Stub#Expression" <: var"##Abstract#Expression"
    node::Union{Nothing,OneOf{<:Union{Float64,ParamRef,VarRef,var"##Stub#Apply"{var"##Stub#Expression"},var"##Stub#Reduce"{var"##Stub#Expression"}}}}
end

struct var"##Stub#Program" <: var"##Abstract#Program"
    sets::Vector{IndexSet}
    indexed_sets::Vector{IndexedSet}
    params::Vector{ParamTable}
    vars::Vector{VarDecl}
    objective::Union{Nothing,var"##Stub#Expression"}
    sense::String
    constraints::Vector{var"##Stub#Constraint"{var"##Stub#Expression"}}
    fix::Vector{FixEntry}
end

const Apply = var"##Stub#Apply"{var"##Stub#Expression"}
Apply(;op = "", args = Vector{Expression}()) = Apply(op, args)
PB.default_values(::Type{Apply}) = (;op = "", args = Vector{Expression}())
PB.field_numbers(::Type{Apply}) = (;op = 1, args = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Apply}, _endpos::Int=0, _group::Bool=false)
    op = ""
    args = PB.BufferedVector{Expression}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            op = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        else
            Base.skip(d, wire_type)
        end
    end
    return Apply(op, args[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Apply)
    initpos = position(e.io)
    !isempty(x.op) && PB.encode(e, 1, x.op)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Apply)
    encoded_size = 0
    !isempty(x.op) && (encoded_size += PB._encoded_size(x.op, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    return encoded_size
end

const ConSet = var"##Stub#ConSet"{var"##Stub#Indicator"}
ConSet(;kind = nothing) = ConSet(kind)
PB.oneof_field_types(::Type{ConSet}) = (;
    kind = (;zero=Zero, nonneg=Nonneg, indicator=Indicator),
)
PB.default_values(::Type{ConSet}) = (;zero = nothing, nonneg = nothing, indicator = nothing)
PB.field_numbers(::Type{ConSet}) = (;zero = 1, nonneg = 2, indicator = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ConSet}, _endpos::Int=0, _group::Bool=false)
    kind = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            kind = OneOf(:zero, PB.decode(d, Ref{Zero}))
        elseif field_number == 2
            kind = OneOf(:nonneg, PB.decode(d, Ref{Nonneg}))
        elseif field_number == 3
            kind = OneOf(:indicator, PB.decode(d, Ref{Indicator}))
        else
            Base.skip(d, wire_type)
        end
    end
    return ConSet(kind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ConSet)
    initpos = position(e.io)
    if isnothing(x.kind);
    elseif x.kind.name === :zero
        PB.encode(e, 1, x.kind[]::Zero)
    elseif x.kind.name === :nonneg
        PB.encode(e, 2, x.kind[]::Nonneg)
    elseif x.kind.name === :indicator
        PB.encode(e, 3, x.kind[]::Indicator)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::ConSet)
    encoded_size = 0
    if isnothing(x.kind);
    elseif x.kind.name === :zero
        encoded_size += PB._encoded_size(x.kind[]::Zero, 1)
    elseif x.kind.name === :nonneg
        encoded_size += PB._encoded_size(x.kind[]::Nonneg, 2)
    elseif x.kind.name === :indicator
        encoded_size += PB._encoded_size(x.kind[]::Indicator, 3)
    end
    return encoded_size
end

const Indicator = var"##Stub#Indicator"
Indicator(;bin = nothing, inner = nothing) = Indicator(bin, inner)
PB.default_values(::Type{Indicator}) = (;bin = nothing, inner = nothing)
PB.field_numbers(::Type{Indicator}) = (;bin = 1, inner = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Indicator}, _endpos::Int=0, _group::Bool=false)
    bin = Ref{Union{Nothing,VarRef}}(nothing)
    inner = Ref{Union{Nothing,ConSet}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, bin)
        elseif field_number == 2
            PB.decode!(d, inner)
        else
            Base.skip(d, wire_type)
        end
    end
    return Indicator(bin[], inner[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Indicator)
    initpos = position(e.io)
    !isnothing(x.bin) && PB.encode(e, 1, x.bin)
    !isnothing(x.inner) && PB.encode(e, 2, x.inner)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Indicator)
    encoded_size = 0
    !isnothing(x.bin) && (encoded_size += PB._encoded_size(x.bin, 1))
    !isnothing(x.inner) && (encoded_size += PB._encoded_size(x.inner, 2))
    return encoded_size
end

const Reduce = var"##Stub#Reduce"{var"##Stub#Expression"}
Reduce(;op = "", idx = "", over = nothing, body = nothing, cond = nothing) = Reduce(op, idx, over, body, cond)
PB.default_values(::Type{Reduce}) = (;op = "", idx = "", over = nothing, body = nothing, cond = nothing)
PB.field_numbers(::Type{Reduce}) = (;op = 1, idx = 2, over = 3, body = 4, cond = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Reduce}, _endpos::Int=0, _group::Bool=false)
    op = ""
    idx = ""
    over = Ref{Union{Nothing,SetRef}}(nothing)
    body = Ref{Union{Nothing,Expression}}(nothing)
    cond = Ref{Union{Nothing,Expression}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            op = PB.decode(d, String)
        elseif field_number == 2
            idx = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, over)
        elseif field_number == 4
            PB.decode!(d, body)
        elseif field_number == 5
            PB.decode!(d, cond)
        else
            Base.skip(d, wire_type)
        end
    end
    return Reduce(op, idx, over[], body[], cond[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Reduce)
    initpos = position(e.io)
    !isempty(x.op) && PB.encode(e, 1, x.op)
    !isempty(x.idx) && PB.encode(e, 2, x.idx)
    !isnothing(x.over) && PB.encode(e, 3, x.over)
    !isnothing(x.body) && PB.encode(e, 4, x.body)
    !isnothing(x.cond) && PB.encode(e, 5, x.cond)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Reduce)
    encoded_size = 0
    !isempty(x.op) && (encoded_size += PB._encoded_size(x.op, 1))
    !isempty(x.idx) && (encoded_size += PB._encoded_size(x.idx, 2))
    !isnothing(x.over) && (encoded_size += PB._encoded_size(x.over, 3))
    !isnothing(x.body) && (encoded_size += PB._encoded_size(x.body, 4))
    !isnothing(x.cond) && (encoded_size += PB._encoded_size(x.cond, 5))
    return encoded_size
end

const Constraint = var"##Stub#Constraint"{var"##Stub#Expression"}
Constraint(;f = nothing, set = nothing, over = Vector{QuantBinding}()) = Constraint(f, set, over)
PB.default_values(::Type{Constraint}) = (;f = nothing, set = nothing, over = Vector{QuantBinding}())
PB.field_numbers(::Type{Constraint}) = (;f = 1, set = 2, over = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Constraint}, _endpos::Int=0, _group::Bool=false)
    f = Ref{Union{Nothing,Expression}}(nothing)
    set = Ref{Union{Nothing,ConSet}}(nothing)
    over = PB.BufferedVector{QuantBinding}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, f)
        elseif field_number == 2
            PB.decode!(d, set)
        elseif field_number == 3
            PB.decode!(d, over)
        else
            Base.skip(d, wire_type)
        end
    end
    return Constraint(f[], set[], over[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Constraint)
    initpos = position(e.io)
    !isnothing(x.f) && PB.encode(e, 1, x.f)
    !isnothing(x.set) && PB.encode(e, 2, x.set)
    !isempty(x.over) && PB.encode(e, 3, x.over)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Constraint)
    encoded_size = 0
    !isnothing(x.f) && (encoded_size += PB._encoded_size(x.f, 1))
    !isnothing(x.set) && (encoded_size += PB._encoded_size(x.set, 2))
    !isempty(x.over) && (encoded_size += PB._encoded_size(x.over, 3))
    return encoded_size
end

const Expression = var"##Stub#Expression"
Expression(;node = nothing) = Expression(node)
PB.oneof_field_types(::Type{Expression}) = (;
    node = (;constant=Float64, param=ParamRef, var=VarRef, apply=Apply, reduce=Reduce),
)
PB.default_values(::Type{Expression}) = (;constant = zero(Float64), param = nothing, var = nothing, apply = nothing, reduce = nothing)
PB.field_numbers(::Type{Expression}) = (;constant = 1, param = 2, var = 3, apply = 4, reduce = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Expression}, _endpos::Int=0, _group::Bool=false)
    node = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            node = OneOf(:constant, PB.decode(d, Float64))
        elseif field_number == 2
            node = OneOf(:param, PB.decode(d, Ref{ParamRef}))
        elseif field_number == 3
            node = OneOf(:var, PB.decode(d, Ref{VarRef}))
        elseif field_number == 4
            node = OneOf(:apply, PB.decode(d, Ref{Apply}))
        elseif field_number == 5
            node = OneOf(:reduce, PB.decode(d, Ref{Reduce}))
        else
            Base.skip(d, wire_type)
        end
    end
    return Expression(node)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Expression)
    initpos = position(e.io)
    if isnothing(x.node);
    elseif x.node.name === :constant
        PB.encode(e, 1, x.node[]::Float64)
    elseif x.node.name === :param
        PB.encode(e, 2, x.node[]::ParamRef)
    elseif x.node.name === :var
        PB.encode(e, 3, x.node[]::VarRef)
    elseif x.node.name === :apply
        PB.encode(e, 4, x.node[]::Apply)
    elseif x.node.name === :reduce
        PB.encode(e, 5, x.node[]::Reduce)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Expression)
    encoded_size = 0
    if isnothing(x.node);
    elseif x.node.name === :constant
        encoded_size += PB._encoded_size(x.node[]::Float64, 1)
    elseif x.node.name === :param
        encoded_size += PB._encoded_size(x.node[]::ParamRef, 2)
    elseif x.node.name === :var
        encoded_size += PB._encoded_size(x.node[]::VarRef, 3)
    elseif x.node.name === :apply
        encoded_size += PB._encoded_size(x.node[]::Apply, 4)
    elseif x.node.name === :reduce
        encoded_size += PB._encoded_size(x.node[]::Reduce, 5)
    end
    return encoded_size
end

const Program = var"##Stub#Program"
Program(;sets = Vector{IndexSet}(), indexed_sets = Vector{IndexedSet}(), params = Vector{ParamTable}(), vars = Vector{VarDecl}(), objective = nothing, sense = "", constraints = Vector{Constraint}(), fix = Vector{FixEntry}()) = Program(sets, indexed_sets, params, vars, objective, sense, constraints, fix)
PB.default_values(::Type{Program}) = (;sets = Vector{IndexSet}(), indexed_sets = Vector{IndexedSet}(), params = Vector{ParamTable}(), vars = Vector{VarDecl}(), objective = nothing, sense = "", constraints = Vector{Constraint}(), fix = Vector{FixEntry}())
PB.field_numbers(::Type{Program}) = (;sets = 1, indexed_sets = 2, params = 3, vars = 4, objective = 5, sense = 6, constraints = 7, fix = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Program}, _endpos::Int=0, _group::Bool=false)
    sets = PB.BufferedVector{IndexSet}()
    indexed_sets = PB.BufferedVector{IndexedSet}()
    params = PB.BufferedVector{ParamTable}()
    vars = PB.BufferedVector{VarDecl}()
    objective = Ref{Union{Nothing,Expression}}(nothing)
    sense = ""
    constraints = PB.BufferedVector{Constraint}()
    fix = PB.BufferedVector{FixEntry}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, sets)
        elseif field_number == 2
            PB.decode!(d, indexed_sets)
        elseif field_number == 3
            PB.decode!(d, params)
        elseif field_number == 4
            PB.decode!(d, vars)
        elseif field_number == 5
            PB.decode!(d, objective)
        elseif field_number == 6
            sense = PB.decode(d, String)
        elseif field_number == 7
            PB.decode!(d, constraints)
        elseif field_number == 8
            PB.decode!(d, fix)
        else
            Base.skip(d, wire_type)
        end
    end
    return Program(sets[], indexed_sets[], params[], vars[], objective[], sense, constraints[], fix[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Program)
    initpos = position(e.io)
    !isempty(x.sets) && PB.encode(e, 1, x.sets)
    !isempty(x.indexed_sets) && PB.encode(e, 2, x.indexed_sets)
    !isempty(x.params) && PB.encode(e, 3, x.params)
    !isempty(x.vars) && PB.encode(e, 4, x.vars)
    !isnothing(x.objective) && PB.encode(e, 5, x.objective)
    !isempty(x.sense) && PB.encode(e, 6, x.sense)
    !isempty(x.constraints) && PB.encode(e, 7, x.constraints)
    !isempty(x.fix) && PB.encode(e, 8, x.fix)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Program)
    encoded_size = 0
    !isempty(x.sets) && (encoded_size += PB._encoded_size(x.sets, 1))
    !isempty(x.indexed_sets) && (encoded_size += PB._encoded_size(x.indexed_sets, 2))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 3))
    !isempty(x.vars) && (encoded_size += PB._encoded_size(x.vars, 4))
    !isnothing(x.objective) && (encoded_size += PB._encoded_size(x.objective, 5))
    !isempty(x.sense) && (encoded_size += PB._encoded_size(x.sense, 6))
    !isempty(x.constraints) && (encoded_size += PB._encoded_size(x.constraints, 7))
    !isempty(x.fix) && (encoded_size += PB._encoded_size(x.fix, 8))
    return encoded_size
end
