# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: (c) 2026 Tim Bode, PGI-12, Forschungszentrum Jülich
"""
QuicoptClient — the Julia client for the Quicopt optimization service.

Write a model in JuMP, hand it to `solve`, and read the answer back. Underneath,
`import_model` turns the JuMP model into a `Program` — what a model *is* to
Quicopt: variables, expressions and constraints as data, in a published,
language-neutral form — `encode` turns that into bytes, and `solve` sends them
over HTTP. There is no solver here; the service does the solving.

The `Program` types are generated from the published `program.proto` via ProtoBuf.jl
(`src/proto/`, regenerated by `gen/gen.jl`), so every dependency is public (`JuMP`,
`ProtoBuf`, `HTTP`, `JSON3`). See the README.
"""
module QuicoptClient

import JuMP
const MOI = JuMP.MOI
import ProtoBuf as PB

export import_model, solve, QuicoptError,
       set_source, set_scenarios, smean, scvar, sfreq_leq, sfreq_geq

include("proto/quicopt/quicopt.jl")   # ProtoBuf.jl-generated Program structs (module quicopt.modeler.v1)
include("wire.jl")                    # a Program ↔ the bytes the service reads

"""
    _CATALOG

Operators the client emits — mirrors the service's published operator catalog. The
server's decoded `Catalog` is the final arbiter; an MOI head outside this set is a
coverage gap to register service-side, never papered over here. The last four are
the scenario aggregators of the stochastic layer (see [`set_source`](@ref)).
"""
const _CATALOG = Set((:+, :-, :*, :/, :^, :sin, :cos, :exp, :log, :sqrt, :abs,
                      :max, :min, :smean, :scvar, :sfreq_leq, :sfreq_geq))

# ── MOI scalar function → Quicopt Expression ─────────────────────────────────

"""
    _expr(f, var) -> Expression

Translate an MOI scalar function `f` into an `Expression` node. `var` is the
closure mapping an `MOI.VariableIndex` to its `Var` node — it carries the
variable-naming convention. Dispatches on the type of `f`:

  - `VariableIndex` → the variable node `var(v)`.
  - `Real` (a bare constant) → a `Const`.
  - `ScalarAffineFunction` → `b + Σ aᵢ xᵢ`.
  - `ScalarQuadraticFunction` → `b + Σ aᵢ xᵢ + ½ xᵀQx`, honouring MOI's ½-scaling
    of the quadratic terms (see the method body).
  - `ScalarNonlinearFunction` → a catalog operator tree, via `_nl`.
"""
_expr(v::MOI.VariableIndex, var) = var(v)
_expr(c::Real, var) = _const(c)

# affine:  b + Σ aᵢ xᵢ
_expr(f::MOI.ScalarAffineFunction, var) =
    _sum(vcat(_const(f.constant),
              _pb.Expression[_apply(:*, _pb.Expression[_const(t.coefficient), var(t.variable)]) for t in f.terms]))

# quadratic: MOI stores ½ xᵀQx + aᵀx + b, so a diagonal term (c,x,x) is ½c·x² and
# an off-diagonal (c,x,y) — held once — is c·x·y.
function _expr(f::MOI.ScalarQuadraticFunction, var)
    terms = _pb.Expression[_const(f.constant)]
    for t in f.affine_terms
        push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient), var(t.variable)]))
    end
    for t in f.quadratic_terms
        if t.variable_1 == t.variable_2
            push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient / 2),
                                                   _apply(:^, _pb.Expression[var(t.variable_1), _const(2.0)])]))
        else
            push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient),
                                                   _apply(:*, _pb.Expression[var(t.variable_1), var(t.variable_2)])]))
        end
    end
    _sum(terms)
end

# nonlinear: a symbol-keyed operator tree mapping ~1:1 onto the operator catalog
_expr(f::MOI.ScalarNonlinearFunction, var) =
    _nl(f.head, _pb.Expression[_expr(a, var) for a in f.args])

"""
    _sum(terms) -> Expression

Combine `terms` into a single additive `Expression`, dropping additive-zero
constants (`Const(0.0)`). Returns `Const(0.0)` when every term is zero, the lone
survivor when only one remains, else an `:+` apply over the survivors. The pruning
is cosmetic and value-preserving.
"""
function _sum(terms)
    nz = _pb.Expression[t for t in terms if !_iszero(t)]
    isempty(nz)     ? _const(0.0) :
    length(nz) == 1 ? nz[1] :
                      _apply(:+, nz)
end

"""
    _nl(head, args) -> Expression

Map an MOI nonlinear operator `head` (a `Symbol`) over `args` onto an `Apply`,
normalising to the catalog's arities: unary `:-` becomes `0 - x`, and an n-ary `:*`
folds into nested binary products. Any other `head` must be in `_CATALOG`.

# Throws
- `ErrorException`: if `head` is outside the operator catalog — an operator the service
  must register before the model can be imported.
"""
function _nl(head::Symbol, args::Vector)
    head === :- && length(args) == 1 && return _apply(:-, _pb.Expression[_const(0.0), args[1]])           # unary minus
    head === :* && length(args) > 2  && return foldl((a, b) -> _apply(:*, _pb.Expression[a, b]), args)    # n-ary ⇒ binary
    head in _CATALOG ||
        error("operator :$head is not in the Quicopt operator catalog — " *
              "it must be added to the service before importing")
    _apply(head, args)
end

# ── variable bounds / integrality from VariableIndex-in-set constraints ──────

"""
    _bound!(lo, hi, dom, vi, s)

Fold a `VariableIndex`-in-set constraint `s` on variable `vi` into the running
bound and domain dictionaries `lo`, `hi`, `dom` (mutated in place). `GreaterThan`/
`LessThan` tighten the lower/upper bound, `EqualTo` pins both, `Interval` sets
both; `ZeroOne` marks the domain binary and clamps it to `[0, 1]`, `Integer` marks
it integer.
"""
_bound!(lo, hi, dom, vi, s::MOI.GreaterThan) = (lo[vi] = max(lo[vi], s.lower))
_bound!(lo, hi, dom, vi, s::MOI.LessThan)    = (hi[vi] = min(hi[vi], s.upper))
_bound!(lo, hi, dom, vi, s::MOI.EqualTo)     = (lo[vi] = hi[vi] = s.value)
_bound!(lo, hi, dom, vi, s::MOI.Interval)    = (lo[vi] = s.lower; hi[vi] = s.upper)
_bound!(lo, hi, dom, vi, ::MOI.ZeroOne)      = (dom[vi] = _pb.Domain.BINARY; lo[vi] = max(lo[vi], 0.0); hi[vi] = min(hi[vi], 1.0))
_bound!(lo, hi, dom, vi, ::MOI.Integer)      = (dom[vi] = _pb.Domain.INTEGER)

# ── function-in-set constraint → Constraint (Zero / Nonneg) ─────────────────

# ── the stochastic layer: sources on JuMP variables, aggregators as heads ────
#
# A stochastic model is authored in JuMP like any other — the stochastic
# constructs are just more functions. A *source* (a random variable) is an
# ordinary JuMP variable marked with `set_source`; the importer emits it as a
# named source declaration and rewrites its occurrences into source references,
# so it never becomes a decision variable. The *aggregators* (`smean`, `scvar`,
# `sfreq_leq`, `sfreq_geq`) build nonlinear expression nodes with stochastic
# operator heads; JuMP stores them symbolically and this package ships them as
# data, so no local evaluator is ever involved — such models solve through the
# service, not through a locally attached optimizer.

# model.ext slot: per-model stochastic declarations, written by the setters
# below and read by `import_model`.
mutable struct _Stochastic
    sources::Dict{MOI.VariableIndex,Pair{Symbol,Any}}  # vi => name => spec
    scenarios::Int                                     # 0 = unset (server default)
    seed::Int                                          # 0 = unset (server default)
end
_stoch!(m::JuMP.Model) = get!(() -> _Stochastic(Dict{MOI.VariableIndex,Pair{Symbol,Any}}(), 0, 0),
                              m.ext, :quicopt_stochastic)::_Stochastic
_stoch(m::JuMP.Model)  = get(m.ext, :quicopt_stochastic, nothing)

function _source_name(v::JuMP.VariableRef, name)
    nm = name === nothing ? Symbol(JuMP.name(v)) : Symbol(name)
    (name === nothing && isempty(JuMP.name(v))) &&
        error("source variable is anonymous — pass a name: set_source(m, v, …; name = :demand)")
    nm
end

function _register_source!(m::JuMP.Model, v::JuMP.VariableRef, nm::Symbol, spec)
    st = _stoch!(m)
    vi = JuMP.index(v)
    for (ovi, decl) in st.sources
        ovi == vi && continue
        decl.first == nm &&
            error("source name :$nm is already taken by another variable — " *
                  "each source is one random variable; declare independent " *
                  "sources as separate variables with distinct names")
    end
    st.sources[vi] = nm => spec
    v
end

"""
    set_source(model, v, head::Symbol, params...; name = Symbol(JuMP.name(v)))

Declare the JuMP variable `v` as a *parametric stochastic source*: a draw from
the distribution `head` (an operator from the service catalog, e.g. `:normal`)
with the given parameters. Parameters may be numbers or deterministic JuMP
expressions. The variable stops being a decision variable — it becomes a named
random variable, and every use of `v` in the objective or constraints refers to
the *same* draw (per scenario). Declare independent sources as separate
variables.

Do not put bounds or integrality on `v` — a source carries a distribution, not
a domain — and close every stochastic subexpression with an aggregator
([`smean`](@ref), [`scvar`](@ref), [`sfreq_leq`](@ref), [`sfreq_geq`](@ref))
before it reaches the objective or a constraint root.

    set_source(model, v, data::AbstractVector{<:Real}; name = …)

The empirical form: `v` takes the given scenario column, one value per
scenario (`length(data)` must equal the count passed to
[`set_scenarios`](@ref)). Several empirical columns are aligned by scenario
index, so jointly-drawn columns preserve their correlation.
"""
set_source(m::JuMP.Model, v::JuMP.VariableRef, head::Symbol, params...; name = nothing) =
    _register_source!(m, v, _source_name(v, name), (head, collect(params)))
set_source(m::JuMP.Model, v::JuMP.VariableRef, data::AbstractVector{<:Real}; name = nothing) =
    _register_source!(m, v, _source_name(v, name), Float64.(data))

"""
    set_scenarios(model, n; seed = nothing)

Set the number of scenarios of the sampled instance (and optionally the draw
seed, ≥ 1). Both are *model data*: they pin the instance, so two solves of the
same model see the same draws. Unset values fall back to the server's defaults
(one scenario; its documented default seed).
"""
function set_scenarios(m::JuMP.Model, n::Integer; seed::Union{Integer,Nothing} = nothing)
    n ≥ 1 || error("scenarios must be ≥ 1, got $n")
    st = _stoch!(m)
    st.scenarios = Int(n)
    if seed !== nothing
        seed ≥ 1 || error("scenario seed must be ≥ 1 (0 is reserved for the server default)")
        st.seed = Int(seed)
    end
    nothing
end

"""
    smean(x) -> NonlinearExpr

The scenario mean `E[x]` — the basic stochastic → deterministic aggregator.
Symbolic: JuMP stores the node and the service evaluates it; attaching a local
optimizer to a model containing one will fail with an unsupported-operator
error, which is expected.
"""
smean(x) = JuMP.NonlinearExpr(:smean, x)

"""
    scvar(x, α) -> NonlinearExpr

The conditional value-at-risk of `x` at level `α ∈ (0, 1)` — the expected value
of `x` over its worst `(1 − α)` tail. `α` must be a plain number.
"""
scvar(x, α::Real) = JuMP.NonlinearExpr(:scvar, x, Float64(α))

"""
    sfreq_leq(x, τ) -> NonlinearExpr
    sfreq_geq(x, τ) -> NonlinearExpr

The scenario frequency of `x ≤ τ` (resp. `x ≥ τ`) — the fraction of scenarios
satisfying the comparison, for chance constraints such as
`@constraint(m, sfreq_leq(demand - stock, 0.0) >= 0.9)`. `τ` must be a plain
number.
"""
sfreq_leq(x, τ::Real) = JuMP.NonlinearExpr(:sfreq_leq, x, Float64(τ))
sfreq_geq(x, τ::Real) = JuMP.NonlinearExpr(:sfreq_geq, x, Float64(τ))
@doc (@doc sfreq_leq) sfreq_geq

# a distribution parameter: a number, or a deterministic JuMP scalar expression
_param_expr(p::Real, var) = _const(p)
_param_expr(p, var)       = _expr(JuMP.moi_function(p), var)

"""
    _minus(f, c) -> Expression

Return `f - c`, or `f` unchanged when `c == 0.0` (an additive identity dropped to
keep the expression graph minimal).
"""
_minus(f, c::Real) = c == 0.0 ? f : _apply(:-, _pb.Expression[f, _const(c)])

"""
    _geq(u, f) -> Expression

Return `u - f`, the residual whose nonnegativity encodes the bound `f ≤ u`.
"""
_geq(u, f) = _apply(:-, _pb.Expression[_const(u), f])

"""
    _con!(cons, f, s)

Append the `Constraint`(s) for a function-in-set constraint `f ∈ s` onto
`cons` (mutated in place). `EqualTo(v)` ⇒ `f − v = 0` (a `Zero` set);
`GreaterThan(l)` ⇒ `f − l ≥ 0` and `LessThan(u)` ⇒ `u − f ≥ 0` (both `Nonneg`);
`Interval(l, u)` emits the two `Nonneg` rows. Every constraint is scalar
(`over = []`).
"""
_con!(cons, f, s::MOI.EqualTo)     = push!(cons, _pb.Constraint(f = _minus(f, s.value), set = _zero(),   over = _pb.QuantBinding[]))
_con!(cons, f, s::MOI.GreaterThan) = push!(cons, _pb.Constraint(f = _minus(f, s.lower), set = _nonneg(), over = _pb.QuantBinding[]))
_con!(cons, f, s::MOI.LessThan)    = push!(cons, _pb.Constraint(f = _geq(s.upper, f),   set = _nonneg(), over = _pb.QuantBinding[]))
function _con!(cons, f, s::MOI.Interval)
    push!(cons, _pb.Constraint(f = _minus(f, s.lower), set = _nonneg(), over = _pb.QuantBinding[]))
    push!(cons, _pb.Constraint(f = _geq(s.upper, f),   set = _nonneg(), over = _pb.QuantBinding[]))
end

"""
    import_model(m::JuMP.Model) -> `Program`

Convert a JuMP/MOI model into a Quicopt `Program`. Reads the model at the MOI
level: each variable becomes a scalar `VarDecl` (`:x{col}`) with its bounds and
domain; the objective and every constraint become Quicopt expressions
(`ScalarNonlinearFunction`/affine/quadratic → the expression graph; `EqualTo` →
`Zero`, `LessThan`/`GreaterThan`/`Interval` → `Nonneg`). The result is a flat
`Program` (no index sets); ±Inf bounds pass through and mean unbounded in that
direction.

Variables marked with [`set_source`](@ref) are emitted as named source
declarations instead of decision variables, their uses rewritten to source
references; the scenario count and seed from [`set_scenarios`](@ref) ride along
as model data. A model with no stochastic marks emits exactly what it always
did.
"""
function import_model(m::JuMP.Model)
    b = JuMP.backend(m)
    vis = MOI.get(b, MOI.ListOfVariableIndices())
    st = _stoch(m)
    srcs = st === nothing ? Dict{MOI.VariableIndex,Pair{Symbol,Any}}() : st.sources
    varname(vi) = Symbol("x", vi.value)
    var(vi) = haskey(srcs, vi) ? _source_ref(srcs[vi].first) : _var(varname(vi))

    lo  = Dict(vi => -Inf for vi in vis)
    hi  = Dict(vi =>  Inf for vi in vis)
    dom = Dict(vi => _pb.Domain.CONTINUOUS for vi in vis)
    for (F, S) in MOI.get(b, MOI.ListOfConstraintTypesPresent())
        F === MOI.VariableIndex || continue
        for ci in MOI.get(b, MOI.ListOfConstraintIndices{F,S}())
            vi = MOI.get(b, MOI.ConstraintFunction(), ci)
            haskey(srcs, vi) &&
                error("source :$(srcs[vi].first) carries bounds or a domain — a source " *
                      "is a random variable with a distribution, not a decision variable; " *
                      "declare it with @variable(m, name) and nothing else")
            _bound!(lo, hi, dom, vi, MOI.get(b, MOI.ConstraintSet(), ci))
        end
    end

    vars = _pb.VarDecl[]
    for vi in vis
        haskey(srcs, vi) && continue   # a source is declared, not a decision variable
        l, u = lo[vi], hi[vi]   # ±Inf passes through: an unbounded direction is the server's to judge
        push!(vars, _pb.VarDecl(name = String(varname(vi)), axes = String[], domain = dom[vi],
                                lower = _scalarbound(l), upper = _scalarbound(u), start = clamp(0.0, l, u)))
    end

    sense = MOI.get(b, MOI.ObjectiveSense()) == MOI.MAX_SENSE ? "max" : "min"
    Fobj = MOI.get(b, MOI.ObjectiveFunctionType())
    objective = _expr(MOI.get(b, MOI.ObjectiveFunction{Fobj}()), var)

    cons = _pb.Constraint[]
    for (F, S) in MOI.get(b, MOI.ListOfConstraintTypesPresent())
        F === MOI.VariableIndex && continue
        for ci in MOI.get(b, MOI.ListOfConstraintIndices{F,S}())
            _con!(cons, _expr(MOI.get(b, MOI.ConstraintFunction(), ci), var), MOI.get(b, MOI.ConstraintSet(), ci))
        end
    end

    # source declarations, in canonical (name-sorted) order
    decls = _pb.SourceDecl[]
    for (vi, decl) in sort(collect(srcs); by = p -> String(p.second.first))
        nm, spec = decl
        kind = spec isa Vector{Float64} ?
            PB.OneOf(:empirical,  _pb.Empirical(data = spec)) :
            PB.OneOf(:parametric, _pb.Parametric(head = String(spec[1]),
                         params = _pb.Expression[_param_expr(p, var) for p in spec[2]]))
        push!(decls, _pb.SourceDecl(name = String(nm), kind = kind))
    end

    _pb.Program(sets = _pb.IndexSet[], indexed_sets = _pb.IndexedSet[], params = _pb.ParamTable[],
                vars = vars, objective = objective, sense = sense,
                constraints = cons, fix = _pb.FixEntry[],
                scenarios = st === nothing ? 0 : UInt64(st.scenarios),
                scenario_seed = st === nothing ? 0 : UInt64(st.seed),
                sources = decls)
end

include("transport.jl")   # solve(model) → POST /v1/solve → parsed result

end # module
