# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: (c) 2026 Tim Bode, PGI-12, Forschungszentrum Jülich
"""
QuicoptClient — the Julia client for the Quicopt API.

Authors a model in JuMP and converts it (`import_model`) to the Quicopt v1 wire
`Program` — the published, language-neutral schema — serializes it to bytes
(`encode`), and solves it over HTTP (`solve`). The wire schema is generated from
`program.proto` via ProtoBuf.jl (`src/proto/`, regenerated by `gen/gen.jl`), so the
client's dependencies are all public (`JuMP`, `ProtoBuf`, `HTTP`, `JSON3`). See the
README.
"""
module QuicoptClient

import JuMP
const MOI = JuMP.MOI
import ProtoBuf as PB

export import_model, solve, QuicoptError

include("proto/quicopt/quicopt.jl")   # ProtoBuf.jl-generated wire structs (module quicopt.modeler.v1)
include("wire.jl")                    # generated structs ↔ bytes (the conformant codec)

"""
    _CATALOG

Operators the client emits — mirrors the service's published operator catalog. The
server's decoded `Catalog` is the final arbiter; an MOI head outside this set is a
coverage gap to register service-side, never papered over here.
"""
const _CATALOG = Set((:+, :-, :*, :/, :^, :sin, :cos, :exp, :log, :sqrt, :abs))

# ── MOI scalar function → wire Expression ────────────────────────────────────

"""
    _expr(f, var) -> Expression

Translate an MOI scalar function `f` into a wire `Expression` node. `var` is the
closure mapping an `MOI.VariableIndex` to its wire `Var` node — it carries the
variable-naming convention. Dispatches on the type of `f`:

  - `VariableIndex` → the variable node `var(v)`.
  - `Real` (a bare constant) → a `Const`.
  - `ScalarAffineFunction` → `b + Σ aᵢ xᵢ`.
  - `ScalarQuadraticFunction` → `b + Σ aᵢ xᵢ + ½ xᵀQx`, honouring MOI's ½-scaling
    of the quadratic terms (see the method body).
  - `ScalarNonlinearFunction` → a catalog operator tree, via `_nl`.
"""
_expr(v::MOI.VariableIndex, var) = var(v)
_expr(c::Real, var) = _const(c)

# affine:  b + Σ aᵢ xᵢ
_expr(f::MOI.ScalarAffineFunction, var) =
    _sum(vcat(_const(f.constant),
              _pb.Expression[_apply(:*, _pb.Expression[_const(t.coefficient), var(t.variable)]) for t in f.terms]))

# quadratic: MOI stores ½ xᵀQx + aᵀx + b, so a diagonal term (c,x,x) is ½c·x² and
# an off-diagonal (c,x,y) — held once — is c·x·y.
function _expr(f::MOI.ScalarQuadraticFunction, var)
    terms = _pb.Expression[_const(f.constant)]
    for t in f.affine_terms
        push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient), var(t.variable)]))
    end
    for t in f.quadratic_terms
        if t.variable_1 == t.variable_2
            push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient / 2),
                                                   _apply(:^, _pb.Expression[var(t.variable_1), _const(2.0)])]))
        else
            push!(terms, _apply(:*, _pb.Expression[_const(t.coefficient),
                                                   _apply(:*, _pb.Expression[var(t.variable_1), var(t.variable_2)])]))
        end
    end
    _sum(terms)
end

# nonlinear: a symbol-keyed operator tree mapping ~1:1 onto the wire catalog
_expr(f::MOI.ScalarNonlinearFunction, var) =
    _nl(f.head, _pb.Expression[_expr(a, var) for a in f.args])

"""
    _sum(terms) -> Expression

Combine `terms` into a single additive `Expression`, dropping additive-zero
constants (`Const(0.0)`). Returns `Const(0.0)` when every term is zero, the lone
survivor when only one remains, else an `:+` apply over the survivors. The pruning
is cosmetic and value-preserving.
"""
function _sum(terms)
    nz = _pb.Expression[t for t in terms if !_iszero(t)]
    isempty(nz)     ? _const(0.0) :
    length(nz) == 1 ? nz[1] :
                      _apply(:+, nz)
end

"""
    _nl(head, args) -> Expression

Map an MOI nonlinear operator `head` (a `Symbol`) over `args` onto a wire `Apply`,
normalising to the catalog's arities: unary `:-` becomes `0 - x`, and an n-ary `:*`
folds into nested binary products. Any other `head` must be in `_CATALOG`.

# Throws
- `ErrorException`: if `head` is outside the wire catalog — an operator the service
  must register before the model can be imported.
"""
function _nl(head::Symbol, args::Vector)
    head === :- && length(args) == 1 && return _apply(:-, _pb.Expression[_const(0.0), args[1]])           # unary minus
    head === :* && length(args) > 2  && return foldl((a, b) -> _apply(:*, _pb.Expression[a, b]), args)    # n-ary ⇒ binary
    head in _CATALOG ||
        error("operator :$head is not in the wire catalog — register it service-side before importing")
    _apply(head, args)
end

# ── variable bounds / integrality from VariableIndex-in-set constraints ──────

"""
    _bound!(lo, hi, dom, vi, s)

Fold a `VariableIndex`-in-set constraint `s` on variable `vi` into the running
bound and domain dictionaries `lo`, `hi`, `dom` (mutated in place). `GreaterThan`/
`LessThan` tighten the lower/upper bound, `EqualTo` pins both, `Interval` sets
both; `ZeroOne` marks the domain binary and clamps it to `[0, 1]`, `Integer` marks
it integer.
"""
_bound!(lo, hi, dom, vi, s::MOI.GreaterThan) = (lo[vi] = max(lo[vi], s.lower))
_bound!(lo, hi, dom, vi, s::MOI.LessThan)    = (hi[vi] = min(hi[vi], s.upper))
_bound!(lo, hi, dom, vi, s::MOI.EqualTo)     = (lo[vi] = hi[vi] = s.value)
_bound!(lo, hi, dom, vi, s::MOI.Interval)    = (lo[vi] = s.lower; hi[vi] = s.upper)
_bound!(lo, hi, dom, vi, ::MOI.ZeroOne)      = (dom[vi] = _pb.Domain.BINARY; lo[vi] = max(lo[vi], 0.0); hi[vi] = min(hi[vi], 1.0))
_bound!(lo, hi, dom, vi, ::MOI.Integer)      = (dom[vi] = _pb.Domain.INTEGER)

# ── function-in-set constraint → wire Constraint (Zero / Nonneg) ─────────────

"""
    _minus(f, c) -> Expression

Return `f - c`, or `f` unchanged when `c == 0.0` (an additive identity dropped to
keep the expression graph minimal).
"""
_minus(f, c::Real) = c == 0.0 ? f : _apply(:-, _pb.Expression[f, _const(c)])

"""
    _geq(u, f) -> Expression

Return `u - f`, the residual whose nonnegativity encodes the bound `f ≤ u`.
"""
_geq(u, f) = _apply(:-, _pb.Expression[_const(u), f])

"""
    _con!(cons, f, s)

Append the wire `Constraint`(s) for a function-in-set constraint `f ∈ s` onto
`cons` (mutated in place). `EqualTo(v)` ⇒ `f − v = 0` (a `Zero` set);
`GreaterThan(l)` ⇒ `f − l ≥ 0` and `LessThan(u)` ⇒ `u − f ≥ 0` (both `Nonneg`);
`Interval(l, u)` emits the two `Nonneg` rows. Every constraint is scalar
(`over = []`).
"""
_con!(cons, f, s::MOI.EqualTo)     = push!(cons, _pb.Constraint(f = _minus(f, s.value), set = _zero(),   over = _pb.QuantBinding[]))
_con!(cons, f, s::MOI.GreaterThan) = push!(cons, _pb.Constraint(f = _minus(f, s.lower), set = _nonneg(), over = _pb.QuantBinding[]))
_con!(cons, f, s::MOI.LessThan)    = push!(cons, _pb.Constraint(f = _geq(s.upper, f),   set = _nonneg(), over = _pb.QuantBinding[]))
function _con!(cons, f, s::MOI.Interval)
    push!(cons, _pb.Constraint(f = _minus(f, s.lower), set = _nonneg(), over = _pb.QuantBinding[]))
    push!(cons, _pb.Constraint(f = _geq(s.upper, f),   set = _nonneg(), over = _pb.QuantBinding[]))
end

"""
    import_model(m::JuMP.Model) -> wire `Program`

Convert a JuMP/MOI model into the Quicopt v1 wire `Program` (the generated
proto struct). Imports at the MOI level: each variable becomes a scalar `VarDecl`
(`:x{col}`) with its bounds and domain; the objective and every function-in-set
constraint become wire expressions (`ScalarNonlinearFunction`/affine/quadratic →
the expression graph; `EqualTo` → `Zero`, `LessThan`/`GreaterThan`/`Interval` →
`Nonneg`). The result is a flat `Program` (no index sets); ±Inf bounds pass through.
"""
function import_model(m::JuMP.Model)
    b = JuMP.backend(m)
    vis = MOI.get(b, MOI.ListOfVariableIndices())
    varname(vi) = Symbol("x", vi.value)
    var(vi) = _var(varname(vi))

    lo  = Dict(vi => -Inf for vi in vis)
    hi  = Dict(vi =>  Inf for vi in vis)
    dom = Dict(vi => _pb.Domain.CONTINUOUS for vi in vis)
    for (F, S) in MOI.get(b, MOI.ListOfConstraintTypesPresent())
        F === MOI.VariableIndex || continue
        for ci in MOI.get(b, MOI.ListOfConstraintIndices{F,S}())
            _bound!(lo, hi, dom, MOI.get(b, MOI.ConstraintFunction(), ci), MOI.get(b, MOI.ConstraintSet(), ci))
        end
    end

    vars = _pb.VarDecl[]
    for vi in vis
        l, u = lo[vi], hi[vi]   # ±Inf passes through: an unbounded direction is the server's to judge
        push!(vars, _pb.VarDecl(name = String(varname(vi)), axes = String[], domain = dom[vi],
                                lower = _scalarbound(l), upper = _scalarbound(u), start = clamp(0.0, l, u)))
    end

    sense = MOI.get(b, MOI.ObjectiveSense()) == MOI.MAX_SENSE ? "max" : "min"
    Fobj = MOI.get(b, MOI.ObjectiveFunctionType())
    objective = _expr(MOI.get(b, MOI.ObjectiveFunction{Fobj}()), var)

    cons = _pb.Constraint[]
    for (F, S) in MOI.get(b, MOI.ListOfConstraintTypesPresent())
        F === MOI.VariableIndex && continue
        for ci in MOI.get(b, MOI.ListOfConstraintIndices{F,S}())
            _con!(cons, _expr(MOI.get(b, MOI.ConstraintFunction(), ci), var), MOI.get(b, MOI.ConstraintSet(), ci))
        end
    end

    _pb.Program(sets = _pb.IndexSet[], indexed_sets = _pb.IndexedSet[], params = _pb.ParamTable[],
                vars = vars, objective = objective, sense = sense,
                constraints = cons, fix = _pb.FixEntry[])
end

include("transport.jl")   # solve(model) → POST /v1/solve → parsed result

end # module
